### ISSUE TITLE
Why isn't feature_valuesused?（model.py:55）

### ISSUE THREAD

**Issue by shawnwhale** [guoyang9/GML-FM#1]
`	def forward(self, features, feature_values):`

Does this function have nothing to do with Feature_values?
`evaluate.py:25    predictions = model(features, feature_values)`
Does predictions also depend on features only ？

**Comment by guoyang9** [comment]
Sorry for the vey late response. 

My initial intention is to support FM values within [0, 1]. But soon I found that current FM papers all adopt {0, 1} value. So that you can understand the features here as feature values with notational abuse. 

For the second question, the user ID and item ID are already included in the feature vector.
